### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by adam-rocska** [mojzesh/swift-colorful#1]
This library fucking kicks ass.

Thanks. Been using it for ~6 months now and so far things look great. Great API, great stability.

Since there was no "GitHub Community" and "Discussion" thingy added, I made a ticket for this ¯\_(ツ)_/¯ sry, but wanted to let you know.

**Comment by mojzesh** [comment]
Hey @adam-rocska thanks for feedback, I'm glad you like it 👍
